parameters:
    postmill.http_client.default_user_agent: "Postmill/%env(APP_VERSION)% (https://postmill.xyz)"
    postmill.http_client.external_client_options:
        headers:
            User-Agent: "%postmill.http_client.default_user_agent%"

services:
    _defaults:
        public: false

    Symfony\Contracts\HttpClient\HttpClientInterface $externalClient: "@postmill.http_client.external_client"

    postmill.http_client.default:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['@Symfony\Contracts\HttpClient\HttpClientInterface', withOptions]
        arguments:
            - "%postmill.http_client.external_client_options%"

    postmill.http_client.external_client:
        class: Symfony\Component\HttpClient\NoPrivateNetworkHttpClient
        arguments: ['@postmill.http_client.default']

    postmill.http_client.external_client.psr18:
        class: Symfony\Component\HttpClient\Psr18Client
        arguments: ['@postmill.http_client.external_client']
